#ifndef KAPLAR_GAME_H_
#define KAPLAR_GAME_H_ 1

#include "common.h"

// PLAYER COMMANDS
#define SV_CMD_PLAYER_LOGIN			0x0001	// MADE UP FOR PARSING
#define SV_CMD_PLAYER_LOGOUT			0x0014
#define SV_CMD_PLAYER_KEEP_ALIVE		0x001E
#define SV_CMD_PLAYER_AUTO_WALK			0x0064
#define SV_CMD_PLAYER_MOVE_NORTH		0x0065
#define SV_CMD_PLAYER_MOVE_EAST			0x0066
#define SV_CMD_PLAYER_MOVE_SOUTH		0x0067
#define SV_CMD_PLAYER_MOVE_WEST			0x0068
#define SV_CMD_PLAYER_STOP_AUTO_WALK		0x0069
#define SV_CMD_PLAYER_MOVE_NORTHEAST		0x006A
#define SV_CMD_PLAYER_MOVE_SOUTHEAST		0x006B
#define SV_CMD_PLAYER_MOVE_SOUTHWEST		0x006C
#define SV_CMD_PLAYER_MOVE_NORTHWEST		0x006D
#define SV_CMD_PLAYER_TURN_NORTH		0x006F
#define SV_CMD_PLAYER_TURN_EAST			0x0070
#define SV_CMD_PLAYER_TURN_SOUTH		0x0071
#define SV_CMD_PLAYER_TURN_WEST			0x0072
#define SV_CMD_PLAYER_ITEM_THROW		0x0078
#define SV_CMD_PLAYER_SHOP_LOOK			0x0079
#define SV_CMD_PLAYER_SHOP_BUY			0x007A
#define SV_CMD_PLAYER_SHOP_SELL			0x007B
#define SV_CMD_PLAYER_SHOP_CLOSE		0x007C
#define SV_CMD_PLAYER_TRADE_REQUEST		0x007D
#define SV_CMD_PLAYER_TRADE_LOOK		0x007E
#define SV_CMD_PLAYER_TRADE_ACCEPT		0x007F
#define SV_CMD_PLAYER_TRADE_CLOSE		0x0080
#define SV_CMD_PLAYER_ITEM_USE			0x0082
#define SV_CMD_PLAYER_ITEM_USE_EX		0x0083
#define SV_CMD_PLAYER_BATTLE_WINDOW		0x0084
#define SV_CMD_PLAYER_ITEM_ROTATE		0x0085
#define SV_CMD_PLAYER_CONTAINER_CLOSE		0x0087
#define SV_CMD_PLAYER_CONTAINER_PARENT		0x0088
#define SV_CMD_PLAYER_ITEM_WRITE		0x0089
#define SV_CMD_PLAYER_HOUSE_WRITE		0x008A
#define SV_CMD_PLAYER_LOOK			0x008C
#define SV_CMD_PLAYER_SAY			0x0096
#define SV_CMD_PLAYER_CHANNELS_REQUEST		0x0097
#define SV_CMD_PLAYER_CHANNEL_OPEN		0x0098
#define SV_CMD_PLAYER_CHANNEL_CLOSE		0x0099
#define SV_CMD_PLAYER_PVT_CHAT_OPEN		0x009A
#define SV_CMD_PLAYER_NPC_CHAT_CLOSE		0x009E
#define SV_CMD_PLAYER_BATTLE_MODE		0x00A0
#define SV_CMD_PLAYER_ATTACK			0x00A1
#define SV_CMD_PLAYER_FOLLOW			0x00A2
#define SV_CMD_PLAYER_PARTY_INVITE		0x00A3
#define SV_CMD_PLAYER_PARTY_JOIN		0x00A4
#define SV_CMD_PLAYER_PARTY_INVITE_REVOKE	0x00A5
#define SV_CMD_PLAYER_PARTY_LEADERSHIP_PASS	0x00A6
#define SV_CMD_PLAYER_PARTY_LEAVE		0x00A7
#define SV_CMD_PLAYER_PARTY_SHARED_EXP		0x00A8
#define SV_CMD_PLAYER_CHANNEL_CREATE		0x00AA
#define SV_CMD_PLAYER_CHANNEL_INVITE		0x00AB
#define SV_CMD_PLAYER_CHANNEL_KICK		0x00AC
#define SV_CMD_PLAYER_HOLD			0x00BE
#define SV_CMD_PLAYER_TILE_UPDATE_REQUEST	0x00C9	// ? SV_CMD_PLAYER_TILE_RESEND
#define SV_CMD_PLAYER_CONTAINER_UPDATE_REQUEST	0x00CA	// ? SV_CMD_PLAYER_CONTAINER_RESEND
#define SV_CMD_PLAYER_OUTFITS_REQUEST		0x00D2
#define SV_CMD_PLAYER_OUTFIT_SET		0x00D3
//#define SV_CMD_PLAYER_MOUNT			0x00D4
#define SV_CMD_PLAYER_VIP_ADD			0x00DC
#define SV_CMD_PLAYER_VIP_REMOVE		0x00DD
//#define SV_CMD_PLAYER_BUG_REPORT		0x00E6
//#define SV_CMD_PLAYER_VIOLATION_WINDOW	0x00E7
//#define SV_CMD_PLAYER_DEBUG_ASSERT		0x00E8
#define SV_CMD_PLAYER_QUESTLOG_REQUEST		0x00F0
#define SV_CMD_PLAYER_QUESTLINE_REQUEST		0x00F1
//#define SV_CMD_PLAYER_VIOLATION_REPORT	0x00F2

bool game_add_server_cmd(uint16 command, uint32 handle, uint8 *data, uint16 datalen);
bool game_add_server_task(void (*fp)(void*), void *arg);

bool game_init(void);
void game_shutdown(void);
void game_run(void);


#endif //KAPLAR_GAME_H
