#ifndef GAME_GAME_H_
#define GAME_GAME_H_

#include "def.h"

bool game_init(void);
void game_shutdown(void);
void game_run(void);

// @TODO: maybe use the same way of sending messages from
// the network thread with the database thread (this will
// require a different input buffer because instead two
// threads would try write to it)
//#define CMD_DBRESULT_ACCOUNT_LOGIN	0xFF01
//#define CMD_DBRESULT_PLAYER_LOGIN	0xFF02

// LOGIN PROTOCOL
#define CMD_ACCOUNT_LOGIN			0x0101	// MADE UP FOR PARSING

// GAME PROTOCOL
//#define MAKE_PLAYER_CMD(opcode)		(uint16)(0x0000 | (opcode))
#define CMD_PLAYER_LOGIN			0x0001	// MADE UP FOR PARSING
#define CMD_PLAYER_LOGOUT			0x0014
#define CMD_PLAYER_KEEP_ALIVE			0x001E
#define CMD_PLAYER_AUTO_WALK			0x0064
#define CMD_PLAYER_MOVE_NORTH			0x0065
#define CMD_PLAYER_MOVE_EAST			0x0066
#define CMD_PLAYER_MOVE_SOUTH			0x0067
#define CMD_PLAYER_MOVE_WEST			0x0068
#define CMD_PLAYER_STOP_AUTO_WALK		0x0069
#define CMD_PLAYER_MOVE_NORTHEAST		0x006A
#define CMD_PLAYER_MOVE_SOUTHEAST		0x006B
#define CMD_PLAYER_MOVE_SOUTHWEST		0x006C
#define CMD_PLAYER_MOVE_NORTHWEST		0x006D
#define CMD_PLAYER_TURN_NORTH			0x006F
#define CMD_PLAYER_TURN_EAST			0x0070
#define CMD_PLAYER_TURN_SOUTH			0x0071
#define CMD_PLAYER_TURN_WEST			0x0072
#define CMD_PLAYER_ITEM_THROW			0x0078
#define CMD_PLAYER_SHOP_LOOK			0x0079
#define CMD_PLAYER_SHOP_BUY			0x007A
#define CMD_PLAYER_SHOP_SELL			0x007B
#define CMD_PLAYER_SHOP_CLOSE			0x007C
#define CMD_PLAYER_TRADE_REQUEST		0x007D
#define CMD_PLAYER_TRADE_LOOK			0x007E
#define CMD_PLAYER_TRADE_ACCEPT			0x007F
#define CMD_PLAYER_TRADE_CLOSE			0x0080
#define CMD_PLAYER_ITEM_USE			0x0082
#define CMD_PLAYER_ITEM_USE_EX			0x0083
#define CMD_PLAYER_BATTLE_WINDOW		0x0084
#define CMD_PLAYER_ITEM_ROTATE			0x0085
#define CMD_PLAYER_CONTAINER_CLOSE		0x0087
#define CMD_PLAYER_CONTAINER_PARENT		0x0088
#define CMD_PLAYER_ITEM_WRITE			0x0089
#define CMD_PLAYER_HOUSE_WRITE			0x008A
#define CMD_PLAYER_LOOK				0x008C
#define CMD_PLAYER_SAY				0x0096
#define CMD_PLAYER_CHANNELS_REQUEST		0x0097
#define CMD_PLAYER_CHANNEL_OPEN			0x0098
#define CMD_PLAYER_CHANNEL_CLOSE		0x0099
#define CMD_PLAYER_PVT_CHAT_OPEN		0x009A
#define CMD_PLAYER_NPC_CHAT_CLOSE		0x009E
#define CMD_PLAYER_BATTLE_MODE			0x00A0
#define CMD_PLAYER_ATTACK			0x00A1
#define CMD_PLAYER_FOLLOW			0x00A2
#define CMD_PLAYER_PARTY_INVITE			0x00A3
#define CMD_PLAYER_PARTY_JOIN			0x00A4
#define CMD_PLAYER_PARTY_INVITE_REVOKE		0x00A5
#define CMD_PLAYER_PARTY_LEADERSHIP_PASS	0x00A6
#define CMD_PLAYER_PARTY_LEAVE			0x00A7
#define CMD_PLAYER_PARTY_SHARED_EXP		0x00A8
#define CMD_PLAYER_CHANNEL_CREATE		0x00AA
#define CMD_PLAYER_CHANNEL_INVITE		0x00AB
#define CMD_PLAYER_CHANNEL_KICK			0x00AC
#define CMD_PLAYER_HOLD				0x00BE
#define CMD_PLAYER_TILE_UPDATE_REQUEST		0x00C9	// ? CMD_PLAYER_TILE_RESEND
#define CMD_PLAYER_CONTAINER_UPDATE_REQUEST	0x00CA	// ? CMD_PLAYER_CONTAINER_RESEND
#define CMD_PLAYER_OUTFITS_REQUEST		0x00D2
#define CMD_PLAYER_OUTFIT_SET			0x00D3
//#define CMD_PLAYER_MOUNT			0x00D4
#define CMD_PLAYER_VIP_ADD			0x00DC
#define CMD_PLAYER_VIP_REMOVE			0x00DD
//#define CMD_PLAYER_BUG_REPORT			0x00E6
//#define CMD_PLAYER_VIOLATION_WINDOW		0x00E7
//#define CMD_PLAYER_DEBUG_ASSERT		0x00E8
#define CMD_PLAYER_QUESTLOG_REQUEST		0x00F0
#define CMD_PLAYER_QUESTLINE_REQUEST		0x00F1
//#define PLAYER_VIOLATION_REPORT		0x00F2

bool game_add_net_input(uint16 command, uint32 command_handle, uint8 *data, uint16 datalen);


#endif //GAME_GAME_H
